# Welcome to Jekyll!
#

# Site settings
title: Anchorlytics
description: Support for exploring the data oceans
owner: Dr. Sean Ho
first_published: 2016
email: anchor@seanho.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anchorlytics.com"
social:
  twitter: https://twitter.com/anchorlytics
  github: https://github.com/anchorlytics
  linkedin-square: https://linkedin.com/in/seanho00
  
# Build settings
sass:
  style: compressed
